plugins {
    id 'java'
}

group = 'uk.minersonline.cloudinator'
version = '1.0-SNAPSHOT'

subprojects {
    repositories {
        mavenCentral()
        maven {
            url = "https://dev.ME1312.net/maven"
        }
        maven {
            name = "papermc-repo"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
        maven { url 'https://jitpack.io' }
    }
}

